on:
  push:
    branches: [ master ]
  pull_request:
jobs:
  windows:
    runs-on: windows-2016
    steps:
      - uses: actions/checkout@v2
      - name: Install
        shell: cmd
        run: |
          call salome_qgis.bat
      - name: Upload
        uses: actions/upload-artifact@v2
        with:
          name: SALOME-9.7.0
          path: C:\work\SALOME-9.7.0

