on:
  push:
    branches: [ master ]
  pull_request:
jobs:
  windows:
    runs-on: windows-2016
    steps:
      - uses: actions/checkout@v2
      - name: Install
        shell: cmd
        run: |
          curl -LO https://files.salome-platform.org/Salome/Salome9.7.0/SALOME-9.7.0.zip
          mkdir C:\work
          7z x SALOME-9.7.0.zip -oC:\work > nul

          git clone https://github.com/janbar/openssl-cmake.git
          cmake -LAH -S openssl-cmake -G "Visual Studio 15 2017 Win64" -DCMAKE_INSTALL_PREFIX=C:/work/SALOME-9.7.0/W64/openssl && cmake --build . --config Release --target install

          git clone --depth 1 https://github.com/madler/zlib.git
          del CMakeCache.txt
          cmake -LAH -S zlib -G "Visual Studio 15 2017 Win64" -DCMAKE_INSTALL_PREFIX=C:/work/SALOME-9.7.0/W64/zlib && cmake --build . --config Release --target install

          curl -LO https://github.com/libexpat/libexpat/archive/refs/tags/R_2_4_3.zip
          7z x R_2_4_3.zip -oC:\work > nul
          del CMakeCache.txt
          cmake -LAH -S C:/work/libexpat-R_2_4_3/expat -G "Visual Studio 15 2017 Win64" -DCMAKE_INSTALL_PREFIX=C:/work/SALOME-9.7.0/W64/expat && cmake --build . --config Release --target install

          curl -LO https://github.com/Exiv2/exiv2/archive/refs/tags/v0.27.5.zip
          7z x v0.27.5.zip -oC:\work > nul
          del CMakeCache.txt
          cmake -LAH -S C:/work/exiv2-0.27.5 -G "Visual Studio 15 2017 Win64" -DCMAKE_INSTALL_PREFIX=C:/work/SALOME-9.7.0/W64/exiv2 -DZLIB_LIBRARY=C:/work/SALOME-9.7.0/W64/zlib/lib/zlib.lib -DZLIB_INCLUDE_DIR=C:/work/SALOME-9.7.0/W64/zlib/include -DEXPAT_LIBRARY=C:/work/SALOME-9.7.0/W64/expat/lib/libexpat.lib -DEXPAT_INCLUDE_DIR=C:/work/SALOME-9.7.0/W64/expat/include && cmake --build . --config Release --target install

          git clone https://github.com/KDE/qca.git && cd qca && git checkout 24e702e6 && git cherry-pick -n f9442206 d6aef82d cfea7339 && cd ..
          del CMakeCache.txt
          cmake -LAH -S qca -G "Visual Studio 15 2017 Win64" -DCMAKE_INSTALL_PREFIX=C:/work/SALOME-9.7.0/W64/qca -DQt5_DIR=C:/work/SALOME-9.7.0/W64/qt/lib/cmake/Qt5 -DOPENSSL_INCLUDE_DIR=C:/work/SALOME-9.7.0/W64/openssl/include -DOPENSSL_SSL_LIBRARY=C:/work/SALOME-9.7.0/W64/openssl/lib/libssl-1_1-x64.lib -DOPENSSL_CRYPTO_LIBRARY=C:/work/SALOME-9.7.0/W64/openssl/lib/libcrypto-1_1-x64.lib -DLIB_EAY_DEBUG=C:/work/SALOME-9.7.0/W64/openssl/lib/libcrypto-1_1-x64.lib -DLIB_EAY_RELEASE=C:/work/SALOME-9.7.0/W64/openssl/lib/libcrypto-1_1-x64.lib -DSSL_EAY_DEBUG=C:/work/SALOME-9.7.0/W64/openssl/lib/libssl-1_1-x64.lib -DSSL_EAY_RELEASE=C:/work/SALOME-9.7.0/W64/openssl/lib/libssl-1_1-x64.lib && cmake --build . --config Release --target install

          curl -LO https://github.com/frankosterfeld/qtkeychain/archive/refs/tags/v0.12.0.zip
          7z x v0.12.0.zip -oC:\work > nul
          del CMakeCache.txt
          cmake -LAH -S C:/work/qtkeychain-0.12.0 -G "Visual Studio 15 2017 Win64" -DCMAKE_INSTALL_PREFIX=C:/work/SALOME-9.7.0/W64/qtkeychain -DQt5_DIR=C:/work/SALOME-9.7.0/W64/qt/lib/cmake/Qt5 && cmake --build . --config Release --target install

          git clone --depth 1 https://gitlab.com/federicomenaquintero/bzip2.git
          del CMakeCache.txt
          cmake -LAH -S bzip2 -G "Visual Studio 15 2017 Win64" -DCMAKE_INSTALL_PREFIX=C:/work/SALOME-9.7.0/W64/bzip2 && cmake --build . --config Release --target install

          curl -LO https://github.com/nih-at/libzip/archive/refs/tags/v1.8.0.zip
          7z x v1.8.0.zip -oC:\work > nul
          del CMakeCache.txt
          cmake -LAH -S C:/work/libzip-1.8.0 -G "Visual Studio 15 2017 Win64" -DCMAKE_INSTALL_PREFIX=C:/work/SALOME-9.7.0/W64/libzip -DZLIB_LIBRARY=C:/work/SALOME-9.7.0/W64/zlib/lib/zlib.lib -DZLIB_INCLUDE_DIR=C:/work/SALOME-9.7.0/W64/zlib/include -DBZIP2_LIBRARIES=C:/work/SALOME-9.7.0/W64/bzip2/lib/bz2.lib -DBZIP2_INCLUDE_DIR=C:/work/SALOME-9.7.0/W64/bzip2/include -DENABLE_BZIP2=OFF && cmake --build . --config Release --target install

          curl -LO https://github.com/zlib-ng/minizip-ng/archive/refs/tags/3.0.4.zip
          7z x 3.0.4.zip -oC:\work > nul
          del CMakeCache.txt
          cmake -LAH -S C:/work/minizip-ng-3.0.4 -G "Visual Studio 15 2017 Win64" -DCMAKE_INSTALL_PREFIX=C:/work/SALOME-9.7.0/W64/minizip -DBZIP2_LIBRARY=C:/work/SALOME-9.7.0/W64/bzip2/lib/bz2.lib -DBZIP2_INCLUDE_DIR=C:/work/SALOME-9.7.0/W64/bzip2/include -DMZ_LZMA=OFF -DZLIB_LIBRARY=C:/work/SALOME-9.7.0/W64/zlib/lib/zlib.lib -DZLIB_INCLUDE_DIR=C:/work/SALOME-9.7.0/W64/zlib/include && cmake --build . --config Release --target install
          
          git clone https://github.com/robotology-dependencies/libxml2-cmake-buildsystem.git
          del CMakeCache.txt
          cmake -LAH -S libxml2-cmake-buildsystem -G "Visual Studio 15 2017 Win64" -DCMAKE_INSTALL_PREFIX=C:/work/SALOME-9.7.0/W64/libxml2 -DZLIB_LIBRARY=C:/work/SALOME-9.7.0/W64/zlib/lib/zlib.lib -DZLIB_INCLUDE_DIR=C:/work/SALOME-9.7.0/W64/zlib/include -DLIBXML2_WITH_LZMA=OFF -DWITH_LZMA=OFF -DLIBXML2_WITH_ICONV=OFF -DWITH_ICONV=OFF && cmake --build . --config Release --target install
          
          curl -LO https://github.com/libjpeg-turbo/libjpeg-turbo/archive/refs/tags/2.1.2.zip
          7z x 2.1.2.zip -oC:\work > nul
          del CMakeCache.txt
          cmake -LAH -S C:/work/libjpeg-turbo-2.1.2 -G "Visual Studio 15 2017 Win64" -DCMAKE_INSTALL_PREFIX=C:/work/SALOME-9.7.0/W64/jpeg && cmake --build . --config Release --target install

          curl -LO https://github.com/libgeos/geos/archive/refs/tags/3.9.2.zip
          7z x 3.9.2.zip -oC:\work > nul
          del CMakeCache.txt
          cmake -LAH -S C:/work/geos-3.9.2 -G "Visual Studio 15 2017 Win64" -DCMAKE_INSTALL_PREFIX=C:/work/SALOME-9.7.0/W64/geos -DBUILD_TESTING=OFF -DBUILD_BENCHMARKS=OFF && cmake --build . --config Release --target install

          git clone --depth 1 https://github.com/azadkuh/sqlite-amalgamation.git
          del CMakeCache.txt
          cmake -LAH -S sqlite-amalgamation -G "Visual Studio 15 2017 Win64" -DCMAKE_INSTALL_PREFIX=C:/work/SALOME-9.7.0/W64/sqlite -DSQLITE_ENABLE_RTREE=ON -DBUILD_SHELL=ON && cmake --build . --config Release --target install

          curl -LO https://github.com/OSGeo/PROJ/archive/refs/tags/8.0.1.zip
          7z x 8.0.1.zip -oC:\work > nul
          del CMakeCache.txt
          cmake -LAH -S C:/work/proj-8.0.1 -G "Visual Studio 15 2017 Win64" -DCMAKE_INSTALL_PREFIX=C:/work/SALOME-9.7.0/W64/proj -DBUILD_SHARED_LIBS=ON -DENABLE_TIFF=OFF -DENABLE_CURL=OFF -DBUILD_PROJSYNC=OFF -DBUILD_TESTING=OFF -DSQLITE3_INCLUDE_DIR=C:/work/SALOME-9.7.0/W64/sqlite/include -DSQLITE3_LIBRARY=C:/work/SALOME-9.7.0/W64/sqlite/lib/sqlite3.lib -DEXE_SQLITE3=C:/work/SALOME-9.7.0/W64/sqlite/bin/sqlite3 && cmake --build . --config Release --target install

          curl -LO https://github.com/OSGeo/gdal/archive/refs/tags/v3.3.1.zip
          7z x v3.3.1.zip -oC:\work > nul
          git clone --depth 1 https://github.com/OSGeo/gdal.git
          del CMakeCache.txt
          cmake -LAH -S gdal -G "Visual Studio 15 2017 Win64" -DCMAKE_INSTALL_PREFIX=C:/work/SALOME-9.7.0/W64/gdal -DPROJ_LIBRARY=C:/work/SALOME-9.7.0/W64/proj/lib/proj.lib -DPROJ_INCLUDE_DIR=C:/work/SALOME-9.7.0/W64/proj/include -DZLIB_LIBRARY=C:/work/SALOME-9.7.0/W64/zlib/lib/zlib.lib -DZLIB_INCLUDE_DIR=C:/work/SALOME-9.7.0/W64/zlib/include -DGDAL_USE_MYSQL=OFF -DGDAL_USE_SQLITE3=OFF -DGDAL_ENABLE_PLUGINS=OFF -DJPEG_LIBRARY=C:/work/SALOME-9.7.0/W64/jpeg/lib/jpeg.lib -DJPEG_INCLUDE_DIR=C:/work/SALOME-9.7.0/W64/jpeg/include -DRENAME_INTERNAL_LIBJPEG_SYMBOLS=OFF -DBUILD_APPS=OFF -DBUILD_CSHARP_BINDINGS=OFF -DBUILD_DOCS=OFF -DBUILD_JAVA_BINDINGS=OFF -DBUILD_PYTHON_BINDINGS=OFF -DBUILD_TESTING=OFF && cmake --build . --config Release --target install

          curl -LO http://www.gaia-gis.it/gaia-sins/libspatialite-5.0.1.zip
          7z x libspatialite-5.0.1.zip -oC:\work > nul
          git clone --depth 1 https://github.com/jschueller/libspatialite.git
          del CMakeCache.txt
          cmake -LAH -S libspatialite -G "Visual Studio 15 2017 Win64" -DCMAKE_INSTALL_PREFIX=C:/work/SALOME-9.7.0/W64/spatialite -DZLIB_LIBRARY=C:/work/SALOME-9.7.0/W64/zlib/lib/zlib.lib -DZLIB_INCLUDE_DIR=C:/work/SALOME-9.7.0/W64/zlib/include -DPROJ_LIBRARY=C:/work/SALOME-9.7.0/W64/proj/lib/proj.lib -DPROJ_INCLUDE_DIR=C:/work/SALOME-9.7.0/W64/proj/include -DGEOS_INCLUDE_DIR=C:/work/SALOME-9.7.0/W64/geos/include -DGEOS_LIBRARY=C:/work/SALOME-9.7.0/W64/geos/lib/geos_c.lib -DMINIZIP_LIBRARY=C:/work/SALOME-9.7.0/W64/minizip/lib/libminizip.lib -DMINIZIP_INCLUDE_DIR=C:/work/SALOME-9.7.0/W64/minizip/include -DLIBXML2_LIBRARY=C:/work/SALOME-9.7.0/W64/libxml2/lib/xml2.lib -DLIBXML2_INCLUDE_DIR=C:/work/SALOME-9.7.0/W64/libxml2/include/libxml2 -DSQLite3_INCLUDE_DIR=C:/work/SALOME-9.7.0/W64/sqlite/include -DSQLite3_LIBRARY=C:/work/SALOME-9.7.0/W64/sqlite/lib/sqlite3.lib && cmake --build . --config Release --target install

          curl -LO https://github.com/libspatialindex/libspatialindex/archive/refs/tags/1.9.3.zip
          7z x 1.9.3.zip -oC:\work > nul
          del CMakeCache.txt
          cmake -LAH -S C:/work/libspatialindex-1.9.3 -G "Visual Studio 15 2017 Win64" -DCMAKE_INSTALL_PREFIX=C:/work/SALOME-9.7.0/W64/spatialindex && cmake --build . --config Release --target install

          curl -LO https://github.com/protocolbuffers/protobuf/archive/refs/tags/v3.16.0.zip
          7z x v3.16.0.zip -oC:\work > nul
          del CMakeCache.txt
          cmake -LAH -S C:/work/protobuf-3.16.0/cmake -G "Visual Studio 15 2017 Win64" -DCMAKE_INSTALL_PREFIX=C:/work/SALOME-9.7.0/W64/protobuf -DZLIB_LIBRARY=C:/work/SALOME-9.7.0/W64/zlib/lib/zlib.lib -DZLIB_INCLUDE_DIR=C:/work/SALOME-9.7.0/W64/zlib/include -Dprotobuf_BUILD_TESTS=OFF && cmake --build . --config Release --target install

          curl -LO https://www.riverbankcomputing.com/static/Downloads/QScintilla/2.13.0/QScintilla_src-2.13.0.zip
          7z x QScintilla_src-2.13.0.zip -oC:\work > nul
          call "C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\VC\Auxiliary\Build\vcvarsall.bat" amd64
          echo "cd C:\work\QScintilla_src-2.13.0\src && C:\work\SALOME-9.7.0\W64\qt\bin\qmake C:\work\QScintilla_src-2.13.0\src\qscintilla.pro && nmake && nmake install"

          git clone --depth 1 https://github.com/nextgis-borsch/lib_qscintilla.git
          del CMakeCache.txt
          cmake -LAH -S lib_qscintilla -G "Visual Studio 15 2017 Win64" -DCMAKE_INSTALL_PREFIX=C:/work/SALOME-9.7.0/W64/qscintilla -DQt5_DIR=C:/work/SALOME-9.7.0/W64/qt/lib/cmake/Qt5 -DZLIB_LIBRARY=C:/work/SALOME-9.7.0/W64/zlib/lib/zlib.lib -DZLIB_INCLUDE_DIR=C:/work/SALOME-9.7.0/W64/zlib/include -DZLIB_DLL=C:/work/SALOME-9.7.0/W64/zlib/bin/zlib.dll && cmake --build . --config Release --target install

          curl -LO https://downloads.sourceforge.net/winflexbison/files/win_flex_bison3-latest.zip
          7z x win_flex_bison3-latest.zip -oC:\work > nul

          curl -LO https://download.qt.io/archive/qt/5.12/5.12.10/submodules/qtbase-everywhere-src-5.12.10.zip
          7z x qtbase-everywhere-src-5.12.10.zip -oC:\work > nul
          call "C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\VC\Auxiliary\Build\vcvarsall.bat" amd64
          call qt-5.12.10.bat
          nmake
          nmake install

          curl -LO https://github.com/qgis/QGIS/archive/refs/tags/final-3_16_16.zip
          7z x final-3_16_16.zip -oC:\work > nul
          dir /p C:\work
          del CMakeCache.txt
          cmake -LAH -S "C:/work/QGIS-final-3_16_16" -G "Visual Studio 15 2017 Win64" -DCMAKE_INSTALL_PREFIX=C:/work/SALOME-9.7.0/W64/qgis -DFLEX_EXECUTABLE=C:/work/win_flex.exe -DBISON_EXECUTABLE=C:/work/win_bison.exe -DGEOS_INCLUDE_DIR=C:/work/SALOME-9.7.0/W64/geos/include -DGEOS_LIBRARY=C:/work/SALOME-9.7.0/W64/geos/lib/geos_c.lib -DGDAL_INCLUDE_DIR=C:/work/SALOME-9.7.0/W64/gdal/include -DGDAL_LIBRARY=C:/work/SALOME-9.7.0/W64/gdal/lib/gdal.lib -DLIBZIP_LIBRARY=C:/work/SALOME-9.7.0/W64/libzip/lib/zip.lib -DLIBZIP_INCLUDE_DIR=C:/work/SALOME-9.7.0/W64/libzip/include -DLIBZIP_CONF_INCLUDE_DIR=C:/work/SALOME-9.7.0/W64/libzip/include -DProtobuf_LIBRARY=C:/work/SALOME-9.7.0/W64/protobuf/lib/libprotobuf.lib -DProtobuf_INCLUDE_DIR=C:/work/SALOME-9.7.0/W64/protobuf/include -DProtobuf_LITE_LIBRARY=C:/work/SALOME-9.7.0/W64/protobuf/lib/libprotobuf-lite.lib -DProtobuf_PROTOC_EXECUTABLE=C:/work/SALOME-9.7.0/W64/protobuf/bin/protoc.exe -DProtobuf_PROTOC_LIBRARY=C:/work/SALOME-9.7.0/W64/protobuf/lib/libprotoc.lib -DSQLITE3_INCLUDE_DIR=C:/work/SALOME-9.7.0/W64/sqlite/include -DSQLITE3_LIBRARY=C:/work/SALOME-9.7.0/W64/sqlite/lib/sqlite3.lib -DZLIB_LIBRARY=C:/work/SALOME-9.7.0/W64/zlib/lib/zlib.lib -DZLIB_INCLUDE_DIR=C:/work/SALOME-9.7.0/W64/zlib/include -DPROJ_LIBRARY=C:/work/SALOME-9.7.0/W64/proj/lib/proj.lib -DPROJ_INCLUDE_DIR=C:/work/SALOME-9.7.0/W64/proj/include -DLIBXML2_LIBRARY=C:/work/SALOME-9.7.0/W64/libxml2/lib/xml2.lib -DLIBXML2_INCLUDE_DIR=C:/work/SALOME-9.7.0/W64/libxml2/include/libxml2 -DEXPAT_LIBRARY=C:/work/SALOME-9.7.0/W64/expat/lib/libexpat.lib -DEXPAT_INCLUDE_DIR=C:/work/SALOME-9.7.0/W64/expat/include -DQt5_DIR=C:/work/SALOME-9.7.0/W64/qt/lib/cmake/Qt5 -DQt5WinExtras_DIR=C:/work/SALOME-9.7.0/W64/qt/lib/cmake/Qt5WinExtras -DQt5LinguistTools_DIR=C:/work/SALOME-9.7.0/W64/qt/lib/cmake/Qt5LinguistTools -DQWT_INCLUDE_DIR=C:/work/SALOME-9.7.0/W64/qwt/include -DQWT_LIBRARY=C:/work/SALOME-9.7.0/W64/qwt/lib/qwt.lib -DQCA_INCLUDE_DIR=C:/work/SALOME-9.7.0/W64/qca/include/Qca-qt5/QtCrypto -DQCA_LIBRARY=C:/work/SALOME-9.7.0/W64/qca/lib/qca-qt5.lib -DEXIV2_INCLUDE_DIR=C:/work/SALOME-9.7.0/W64/exiv2/include -DEXIV2_LIBRARY=C:/work/SALOME-9.7.0/W64/exiv2/lib/exiv2.lib -DQTKEYCHAIN_LIBRARY=C:/work/SALOME-9.7.0/W64/qtkeychain/lib/qt5keychain.lib -DQTKEYCHAIN_INCLUDE_DIR=C:/work/SALOME-9.7.0/W64/qtkeychain/include/qt5keychain -DQSCINTILLA_INCLUDE_DIR=C:/work/SALOME-9.7.0/W64/qscintilla/include/qscintilla -DQSCINTILLA_LIBRARY=C:/work/SALOME-9.7.0/W64/qscintilla/lib/qscintilla.lib -DSPATIALITE_LIBRARY=C:/work/SALOME-9.7.0/W64/spatialite/lib/spatialite.lib -DSPATIALITE_INCLUDE_DIR=C:/work/SALOME-9.7.0/W64/spatialite/include/ -DSPATIALINDEX_INCLUDE_DIR=C:/work/SALOME-9.7.0/W64/spatialindex/include -DSPATIALINDEX_LIBRARY=C:/work/SALOME-9.7.0/W64/spatialindex/lib/spatialindex-64.lib -DWITH_QTWEBKIT=FALSE -DWITH_GEOREFERENCER=FALSE -DWITH_3D=OFF -DWITH_BINDINGS=OFF -DWITH_SERVER=OFF -DWITH_CUSTOM_WIDGETS=OFF -DWITH_QUICK=OFF -DWITH_QGIS_PROCESS=OFF -DWITH_POSTGRESQL=OFF -DENABLE_TESTS=OFF -DWITH_QSPATIALITE=OFF -DWITH_GRASS7=OFF -DMSVC_RUNTIME_LIBRARY=MultiThreadedDLL && cmake --build . --config Release --target install

