on:
  push:
    branches: [ mainwin ]
  pull_request:
jobs:
  windows:
    runs-on: windows-2016
    steps:
      - uses: actions/checkout@v2
      - name: Install
        shell: cmd
        run: |
          cd mainwin
          cmake -G "Visual Studio 15 2017" -A x64 .
          cmake --build . --config Release
      - name: Upload
        uses: actions/upload-artifact@v2
        with:
          name: mainwin
          path: mainwin\Release\qgis-bin.exe

