on:
  push:
    branches: [ master ]
  pull_request:
jobs:
  windows:
    runs-on: windows-2016
    steps:
      - uses: actions/checkout@v2
      - name: Install
        shell: cmd
        run: |
          call salome_qgis.bat
          

